### ISSUE TITLE
Service Power is unavailable

### ISSUE THREAD

**Issue by lyl15151865258** [SoftBankRoboticsEurope/maplocalizeandmove#2]
07-31 17:10:15.468 21378-21409/com.softbankrobotics.maplocalizeandmove W/QiServices: Service Power is not available
07-31 17:10:15.469 21378-21397/com.softbankrobotics.maplocalizeandmove W/System.err: Uncaught exception on Future: Cannot find service 'Power' in index
07-31 17:10:15.469 21378-21397/com.softbankrobotics.maplocalizeandmove W/System.err: com.aldebaran.qi.QiException: Cannot find service 'Power' in index
07-31 17:10:15.469 21378-21397/com.softbankrobotics.maplocalizeandmove W/System.err:     at com.aldebaran.qi.Future.qiFutureCallGet(Native Method)
07-31 17:10:15.469 21378-21397/com.softbankrobotics.maplocalizeandmove W/System.err:     at com.aldebaran.qi.Future.get(Future.java:238)
07-31 17:10:15.470 21378-21397/com.softbankrobotics.maplocalizeandmove W/System.err:     at com.aldebaran.qi.Future.get(Future.java:273)
07-31 17:10:15.470 21378-21397/com.softbankrobotics.maplocalizeandmove W/System.err:     at com.aldebaran.qi.Future.getError(Future.java:308)
07-31 17:10:15.470 21378-21397/com.softbankrobotics.maplocalizeandmove W/System.err:     at com.aldebaran.qi.Future$ReportBugConsumer.consume(Future.java:43)
07-31 17:10:15.470 21378-21397/com.softbankrobotics.maplocalizeandmove W/System.err:     at com.aldebaran.qi.Future$ReportBugConsumer.consume(Future.java:35)
07-31 17:10:15.594 21378-21410/com.softbankrobotics.maplocalizeandmove D/MSI_MapLocalizeAndMove: onRobotFocusedGained
07-31 17:10:15.596 21378-21410/com.softbankrobotics.maplocalizeandmove E/QiContext: onFocusGained: Error
    com.aldebaran.qi.sdk.exceptions.ServiceUnavailableException: Service Power is unavailable
        at com.aldebaran.qi.sdk.QiContext.getPower(QiContext.java:268)
        at com.softbankrobotics.maplocalizeandmove.Utils.RobotHelper.onRobotFocusGained(RobotHelper.java:39)
        at com.softbankrobotics.maplocalizeandmove.MainActivity.onRobotFocusGained(MainActivity.java:97)
        at com.aldebaran.qi.sdk.QiContext.onFocusGained(QiContext.java:345)
        at com.aldebaran.qi.sdk.core.FocusManager.notifyFocus(FocusManager.java:239)
        at com.aldebaran.qi.sdk.core.FocusManager.access$600(FocusManager.java:30)
        at com.aldebaran.qi.sdk.core.FocusManager$1.run(FocusManager.java:208)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

**Comment by renythomas** [comment]
Hello,
The Power Service is not available on Pepper running a naoqi version less than 2.9.4.

**Comment by lyl15151865258** [comment]
> 您好，
> 运行Naoqi版本低于2.9.4的Pepper上不提供Power Service。

Thank you!
